### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by EriTang** [t2vee/Logto-USS#17]

**Comment by t2vee** [comment]
Apologies for the slow response,
I have been migrating the project away from using workers which will greatly simplify the install process.

You can find the new install instructions in the Readme, feel free to reopen this issue if you come across any issues!

**Comment by EriTang** [comment]
01:07:16.589 | ✘ [ERROR] 15 error(s) and 0 warning(s) when compiling Worker.
-- | --
01:07:16.589 |  
01:07:16.589 |  
01:07:16.592 |  
01:07:16.594 | ✘ [ERROR] Could not resolve "bad-words"
01:07:16.594 |  
01:07:16.594 | ../api/libs/DataValidator/index.js:4:19:
01:07:16.594 | 4 │ import Filter from "bad-words";
01:07:16.594 | ╵                    ~~~~~~~~~~~
01:07:16.594 |  
01:07:16.595 | You can mark the path "bad-words" as external to exclude it from the bundle, which will remove this error.
01:07:16.595 |  
01:07:16.595 |  
01:07:16.595 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.595 |  
01:07:16.595 | ../api/libs/DataValidator/index.js:9:23:
01:07:16.595 | 9 │ import { assert } from 'superstruct'
01:07:16.595 | ╵                        ~~~~~~~~~~~~~
01:07:16.595 |  
01:07:16.595 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.595 |  
01:07:16.595 |  
01:07:16.596 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.596 |  
01:07:16.596 | ../api/libs/DataValidator/schemas/birthday.js:4:40:
01:07:16.596 | 4 │ import { object, string, pattern } from 'superstruct'
01:07:16.596 | ╵                                         ~~~~~~~~~~~~~
01:07:16.596 |  
01:07:16.596 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.596 |  
01:07:16.596 |  
01:07:16.596 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.596 |  
01:07:16.596 | ../api/libs/DataValidator/schemas/developer.js:3:32:
01:07:16.596 | 3 │ import { object, boolean } from 'superstruct'
01:07:16.597 | ╵                                 ~~~~~~~~~~~~~
01:07:16.597 |  
01:07:16.597 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.597 |  
01:07:16.597 |  
01:07:16.597 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.597 |  
01:07:16.597 | ../api/libs/DataValidator/schemas/email.js:3:31:
01:07:16.597 | 3 │ import { object, define } from 'superstruct'
01:07:16.597 | ╵                                ~~~~~~~~~~~~~
01:07:16.598 |  
01:07:16.598 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.598 |  
01:07:16.598 |  
01:07:16.598 | ✘ [ERROR] Could not resolve "is-email"
01:07:16.598 |  
01:07:16.598 | ../api/libs/DataValidator/schemas/email.js:4:20:
01:07:16.598 | 4 │ import isEmail from 'is-email'
01:07:16.598 | ╵                     ~~~~~~~~~~
01:07:16.598 |  
01:07:16.599 | You can mark the path "is-email" as external to exclude it from the bundle, which will remove this error.
01:07:16.599 |  
01:07:16.599 |  
01:07:16.599 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.599 |  
01:07:16.599 | ../api/libs/DataValidator/schemas/locale.js:3:30:
01:07:16.599 | 3 │ import { object, enums } from 'superstruct'
01:07:16.599 | ╵                               ~~~~~~~~~~~~~
01:07:16.600 |  
01:07:16.601 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.601 |  
01:07:16.601 |  
01:07:16.601 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.601 |  
01:07:16.601 | ../api/libs/DataValidator/schemas/name.js:3:40:
01:07:16.601 | 3 │ import { object, string, pattern } from 'superstruct'
01:07:16.601 | ╵                                         ~~~~~~~~~~~~~
01:07:16.601 |  
01:07:16.602 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.602 |  
01:07:16.602 |  
01:07:16.602 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.602 |  
01:07:16.602 | ../api/libs/DataValidator/schemas/password.js:3:40:
01:07:16.602 | 3 │ import { object, string, pattern } from 'superstruct'
01:07:16.602 | ╵                                         ~~~~~~~~~~~~~
01:07:16.602 |  
01:07:16.602 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.603 |  
01:07:16.603 |  
01:07:16.603 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.603 |  
01:07:16.603 | ../api/libs/DataValidator/schemas/phone.js:3:40:
01:07:16.603 | 3 │ import { object, string, pattern } from 'superstruct'
01:07:16.603 | ╵                                         ~~~~~~~~~~~~~
01:07:16.603 |  
01:07:16.603 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.603 |  
01:07:16.604 |  
01:07:16.604 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.604 |  
01:07:16.604 | ../api/libs/DataValidator/schemas/regional.js:3:40:
01:07:16.604 | 3 │ import { object, enums, optional } from 'superstruct'
01:07:16.604 | ╵                                         ~~~~~~~~~~~~~
01:07:16.604 |  
01:07:16.604 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.604 |  
01:07:16.604 |  
01:07:16.605 | ✘ [ERROR] Could not resolve "superstruct"
01:07:16.605 |  
01:07:16.605 | ../api/libs/DataValidator/schemas/username.js:3:40:
01:07:16.605 | 3 │ import { object, string, pattern } from 'superstruct'
01:07:16.605 | ╵                                         ~~~~~~~~~~~~~
01:07:16.605 |  
01:07:16.605 | You can mark the path "superstruct" as external to exclude it from the bundle, which will remove this error.
01:07:16.605 |  
01:07:16.605 |  
01:07:16.605 | ✘ [ERROR] Could not resolve "@cf-wasm/photon"
01:07:16.605 |  
01:07:16.606 | ../api/utils/processAvatar.js:4:24:
01:07:16.606 | 4 │ import * as photon from '@cf-wasm/photon'
01:07:16.606 | ╵                         ~~~~~~~~~~~~~~~~~
01:07:16.606 |  
01:07:16.606 | You can mark the path "@cf-wasm/photon" as external to exclude it from the bundle, which will remove this error.
01:07:16.606 |  
01:07:16.606 |  
01:07:16.606 | ✘ [ERROR] Could not resolve "jose"
01:07:16.606 |  
01:07:16.606 | ../api/utils/verifyAuthToken.js:6:46:
01:07:16.606 | 6 │ import { createRemoteJWKSet, jwtVerify } from 'jose';
01:07:16.606 | ╵                                               ~~~~~~
01:07:16.606 |  
01:07:16.606 | You can mark the path "jose" as external to exclude it from the bundle, which will remove this error.
01:07:16.606 |  
01:07:16.606 |  
01:07:16.607 | ✘ [ERROR] Could not resolve "bad-words"
01:07:16.607 |  
01:07:16.607 | api/v2/utils/check-username-exists/[username].js:6:19:
01:07:16.607 | 6 │ import Filter from "bad-words";
01:07:16.607 | ╵                    ~~~~~~~~~~~
01:07:16.607 |  
01:07:16.607 | You can mark the path "bad-words" as external to exclude it from the bundle, which will remove this error.
01:07:16.607 |  
01:07:16.607 |  
01:07:16.607 | ✘ [ERROR] Build failed with 15 errors:
01:07:16.607 |  
01:07:16.607 | ../api/libs/DataValidator/index.js:4:19: ERROR: Could not resolve "bad-words"
01:07:16.607 | ../api/libs/DataValidator/index.js:9:23: ERROR: Could not resolve "superstruct"
01:07:16.607 | ../api/libs/DataValidator/schemas/birthday.js:4:40: ERROR: Could not resolve "superstruct"
01:07:16.607 | ../api/libs/DataValidator/schemas/developer.js:3:32: ERROR: Could not resolve "superstruct"
01:07:16.607 | ../api/libs/DataValidator/schemas/email.js:3:31: ERROR: Could not resolve "superstruct"
01:07:16.608 | ...
